train_args:
  trainer_type: "encoder"
  num_epochs: 1 
  learning_rate: 2.0e-4
  weight_decay: 0.01
  warmup_steps: 700
  cooldown_steps: null
  checkpoint: null
  wandb: true
  wandb_run_name: "modern-bert-main-unsupervised"
  wandb_project_name: "hrag"
  wandb_entity: "gpt4all"
  log_grads_every: 100
  log_lr_every: 10
  save_every: 2500 
  chunk_size: 512
  output_dir: "ckpts/modern-bert-main-unsupervised"
  # if using deepspeed, this will be ignored
  schedule_type: "cosine"
  max_grad_norm: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  grad_cache: true
  loss_fn: "clip"
  use_fp8: false
  clamp_logits: false
  logit_max: 100
  eval_strategy: "steps"
  eval_steps: 3000

model_args:
  model_type: "modernbert"
  logit_scale: 50
  trainable_logit_scale: false
  seq_len: 128
  pooling: "mean"
  add_prefix: true
  # tokenizer_name: "nomic-ai/modern-nomic-embed-unsup"
  # model_name: "nomic-ai/modern-nomic-embed-unsup"
  tokenizer_name: "answerdotai/ModernBERT-base"
  model_name: "answerdotai/ModernBERT-base"
  pretrained: true
  gradient_checkpointing: false

data_args:
  input_shards: "configs/data/hf_pretrain_pairs.yaml"
  workers: 8
  batch_size: 16384
  seed: 42
  streaming: true
  shuffle: false
  download: true
